export { default as RegisterRouter } from './register'
export { default as MovieRouter } from './movie'
export { default as GenreRouter } from './genre'
export { default as CrudMovieRouter } from './movies'
export { default as QuoteRouter } from './quote'
export { default as SingleQuotes } from './quotes'
