openapi: 3.0.0
info:
  title: Music Band Dashboard
  description: Music Band Control Panel
  version: 1.0.0

servers:
  - url: http://localhost:4242/
    description: local server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /user/register:
    post:
      tags:
        - Authorization
      requestBody:
        content:
          application/json:
            schema:
              properties:
                userName:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                repeatPassword:
                  type: string
                  required: true
              example:
                userName: omari32
                email: test@gmail.com
                password: '12345678'
                repeatPassword: '12345678'

      responses:
        '200':
          description: User Auth.
          content:
            application/json:
              example: 'Confirm Email sent'
