export { default as validateRegister } from './register'
export { default as validateLogin } from './login'
export { default as validateGoogle } from './google'
export { default as validatePasswordRecover } from './recover'
export { default as validateMovie } from './movie'
